// Navigation
export const SET_ACTIVE_SCREEN   = 'SET_ACTIVE_SCREEN'
export const SET_PREVIOUS_SCREEN = 'SET_PREVIOUS_SCREEN'
export const SET_SHOW_NAVBAR     = 'SET_SHOW_NAVBAR'
export const SET_NAVBAR_TAB      = 'SET_NAVBAR_TAB'
export const NAVIGATE_FORWARD    = 'NAV_FORWARD'
export const NAVIGATE_BACK       = 'NAV_BACK'

// Reset
export const RESET_STATE_PASSAGE = 'RESET_STATE_PASSAGE'
export const RESET_STATE_CURRENT_USER_RAVEL_FETCH = 'RESET_STATE_CURRENT_USER_RAVEL_FETCH'
export const RESET_STATE_REPORT = 'RESET_STATE_REPORT'
export const RESET_STATE_ADMIN = 'RESET_STATE_ADMIN'
export const RESET_STATE_USER = 'RESET_STATE_USER'
export const RESET_STATE_SEARCH = 'RESET_STATE_SEARCH'
export const RESET_STATE_RAVEL = 'RESET_STATE_RAVEL'
export const RESET_STATE_NOTIFICATION = 'RESET_STATE_NOTIFICATION'
export const RESET_STATE_MASTER_USER_FETCH = 'RESET_STATE_MASTER_USER_FETCH'
export const RESET_STATE_MASTER_RAVEL = 'RESET_STATE_MASTER_RAVEL'
