# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Google/SignIn'
pod 'Firebase/Core'

target 'raveltree' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for raveltree

  #target 'raveltree-tvOSTests' do
   # inherit! :search_paths
    # Pods for testing
  #end

  target 'raveltreeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'raveltree-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for raveltree-tvOS

 # target 'raveltree-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

#end
