// Author:   Frank Fusco
// Created:  04/12/18
// Modified: 04/12/18
//
// An array of tags for RavelTree.

export const TAGS = [
  'Adventure',
  'Arts',
  'Autobiography',
  'Biography',
  'Business',
  'Children',
  'Classics',
  'Comedy',
  'Coming of Age',
  'Contemporary',
  'Crafts',
  'Engineering',
  'Entertainment',
  'Fantasy',
  'Fitness',
  'Food',
  'Health',
  'History',
  'Hobbies',
  'Home',
  'Humor',
  'Law',
  'Literature',
  'Math',
  'Medical',
  'Memoir',
  'Money',
  'Mystery',
  'Outdoors',
  'Paranormal',
  'Parenting',
  'Philosophy',
  'Photography',
  'Politics',
  'Postmodernism',
  'Reference',
  'Relationships',
  'Religion',
  'Romance',
  'Science Fiction',
  'Science',
  'Self-Help',
  'Social Science',
  'Spirituality',
  'Sports',
  'Suspense',
  'Technology',
  'Teen',
  'Test Preparation',
  'Thriller',
  'Transportation',
  'Travel',
  'Unconventional',
  'Urban Fantasy',
  'Young Adult',
];
